export const userInterests: string[] = [
  "Technology",
  "Programming",
  "Writing",
  "Religion",
  "Business",
  "Education",
  "Data science",
  "Data science",
  "Culture",
  "Science",
  "Health",
  "UI/UX",
  "Lifestyle",
  "Sports",
  "Arts",
  "Music",
  "Food",
  "Books",
  "Housing",
  "Startup",
  "Marketing",
  "Product Management",
  "Entrepreneurship",
  "Artificial Intelligence",
];
