export const postCategories = [
  { name: "Technology" },
  { name: "Programming" },
  { name: "Writing" },
  { name: "Religion" },
  { name: "Business" },
  { name: "Education" },
  { name: "Data science" },
  { name: "Finance" },
  { name: "Culture" },
  { name: "Science" },
  { name: "Health" },
  { name: "UI/UX" },
  { name: "Lifestyle" },
  { name: "Sports" },
  { name: "Arts" },
  { name: "Food" },
  { name: "Books" },
  { name: "Housing" },
  { name: "Startup" },
  { name: "Marketing" },
  { name: "Product Management" },
  { name: "Entrepreneurship" },
  { name: "Artificial Intelligence" },
];
